#host: '127.0.0.1'
#port: 8848
#namespace: '5ec3f2b1-203f-4a93-a8a0-461d24e97f30'
#user: 'nacos'
#password: 'nacos'
#dataid: 'user-web.json'
#group: 'DEFAULT_GROUP'
host: '127.0.0.1'
port: 8848
namespace: '5ec3f2b1-203f-4a93-a8a0-461d24e97f30'
user: 'nacos'
password: 'nacos'
dataid: 'user-web.json'
group: 'DEFAULT_GROUP'
